### ISSUE TITLE
In der Dok Kardinalität für TaxAmout korrigieren

### ISSUE THREAD

**Issue by digitalsigi** [austriapro/ebinterface-standards#18]
In der Doku ist in den Diagrammen zu `TaxItem, OtherVATableTaxListLineItem/TaxAmount` richtig als optional eingezeichnet. In der jeweils  nachfolgenden Tabelle ist die Kardinalität mit `1..1` statt `0..1` angegeben.

**Comment by digitalsigi** [comment]
Wird TaxAmount im Tax Element der eRechnung auf Root Ebene nicht angegeben führt das bei erechnung.gv.at zu einem Fehler. Nach meinem Verständnis müsste der TaxAmount hier - so wie vom Bund verlangt - sehr wohl angegeben werden. Es müsste zumindest in der Dokumentationdarauch hingewiesen oder das xsd geändert  werden.

**Comment by phax** [comment]
@digitalsigi danke für die Meldung.
Der einzige Grund, der mir einfällt, weshalb der `TaxAmount` optional sein könnte ist der, dass es "eh immer" aus den Prozenten berechnet werden kann.
Grundsätzlich würde ich das aber als Fehler im XSD einstufen, und in einem evtl. notwendigen 5.1 fixen. Ich fürchte ein nachträgliches ändern der XSD wäre nicht gut. Aber ein Hinweis in der 5.0er Doku wäre auf jeden Fall gut.

**Comment by digitalsigi** [comment]
Nachträglich ändern ist wirklich kein gute Idee. V5.1 finde ich gut.

**Comment by phax** [comment]
Ich habs auch mal ins Forum, in den 5.1 Wunschlisten Thread gestellt

**Comment by pliegl** [comment]
@digitalsigi Fehler bez. der Kardinallität von TaxAmount wurde in der Doku korrigiert

**Comment by digitalsigi** [comment]
@pliegl Danke für die Info. Bin aus dem Projekt raus.
